// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBibleTools.Commentaries.Model;

namespace MyBibleTools.Commentaries.Migrations
{
    [DbContext(typeof(MyBibleCommentaryDbContext))]
    [Migration("20200918122052_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("MyBibleTools.Commentaries.Model.Commentary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Book")
                        .HasColumnName("book_number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnName("text")
                        .HasColumnType("TEXT");

                    b.Property<int>("FromChapter")
                        .HasColumnName("chapter_number_from")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromVerse")
                        .HasColumnName("verse_number_from")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToChapter")
                        .HasColumnName("chapter_number_to")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToVerse")
                        .HasColumnName("verse_number_to")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Book", "FromChapter", "ToChapter");

                    b.ToTable("commentaries");
                });

            modelBuilder.Entity("MyBibleTools.Commentaries.Model.Info", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnName("value ")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("info");
                });
#pragma warning restore 612, 618
        }
    }
}
